const state={summary:null,creators:[],filtered:[],visible:12,platform:'',status:'',sort:'name',mode:'new'};
const statusLabels={active:'กำลังทำกิจกรรม',hiatus:'พักกิจกรรม',inactive:'ไม่พบกิจกรรมล่าสุด',graduated:'Graduated',unknown:'ไม่ทราบ'};
const platformLabels={youtube:'YouTube',x:'X / Twitter',twitch:'Twitch',tiktok:'TikTok',facebook:'Facebook',bluesky:'Bluesky',instagram:'Instagram'};
const platformIcons={youtube:'smart_display',x:'tag',twitch:'live_tv',tiktok:'movie',facebook:'public',bluesky:'cloud',instagram:'photo_camera'};
const fmt=n=>Number.isFinite(n)?new Intl.NumberFormat('th-TH').format(n):'—';
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const pct=(a,b)=>Number.isFinite(a)&&Number.isFinite(b)&&b>0?Math.round(a/b*100):null;
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const platformName=p=>platformLabels[p]||p;

async function json(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(String(r.status));return r.json()}
async function load(){
  try{state.summary=await json('./data/public-summary.json')}catch{state.summary=await json('./data/bootstrap-summary.json')}
  try{const d=await json('./data/public-creators.json');state.creators=Array.isArray(d.creators)?d.creators:[]}catch{state.creators=[]}
  renderOverview();setupDirectory();setupContribution();route();
}
function generatedLabel(){const raw=state.summary?.meta?.generated_at;if(!raw)return '—';const d=new Date(raw);return Number.isNaN(d.getTime())?'—':d.toLocaleString('th-TH',{dateStyle:'medium',timeStyle:'short'})}
function renderOverview(){
  const s=state.summary||{},platforms=Array.isArray(s.platforms)?s.platforms:[],lifecycle=Array.isArray(s.lifecycle)?s.lifecycle:[],total=s.total_vtubers;
  const pMap=Object.fromEntries(platforms.map(x=>[x.platform,x.count]));
  const active=(lifecycle.find(x=>x.status==='active')||{}).count;
  const cards=[
    {label:'VTuber ทั้งหมด',value:total,unit:'คน',note:'นับตามตัวตน/ระเบียนที่จัดกลุ่ม',icon:'person'},
    {label:'Active ในทะเบียน',value:active,unit:'คน',note:'สถานะ lifecycle ไม่ใช่ live status',icon:'radio_button_checked'},
    {label:'มี YouTube',value:pMap.youtube,unit:'คน',note:'มีอย่างน้อยหนึ่งช่อง YouTube',icon:'smart_display'},
    {label:'มี X / Twitter',value:pMap.x,unit:'คน',note:'มีอย่างน้อยหนึ่งบัญชี X',icon:'tag'},
    {label:'มี Twitch',value:pMap.twitch,unit:'คน',note:'มีอย่างน้อยหนึ่งช่อง Twitch',icon:'sports_esports'}
  ];
  document.querySelector('#summaryCards').innerHTML=cards.map(c=>`<article class="card kpi-card"><div class="kpi-top"><span class="kpi-label">${c.label}</span><span class="kpi-pct">${pct(c.value,total)==null?'—':pct(c.value,total)+'%'}</span></div><div class="kpi-value"><strong>${fmt(c.value)}</strong><small>${c.unit}</small></div><div class="kpi-note"><span class="material-symbols-outlined">${c.icon}</span>${c.note}</div></article>`).join('');
  const updated=generatedLabel();document.querySelector('#headerUpdated').textContent='อัปเดตล่าสุด: '+updated;document.querySelector('#overviewUpdated').textContent='อัปเดต: '+updated;
  document.querySelector('#platformCoverage').textContent=Number.isFinite(total)?`ฐาน ${fmt(total)} รายการ`:'—';
  renderPlatforms(platforms,total);renderLifecycle(lifecycle,total);renderClassification(total);renderTrend(s.debut_trend||[],s.known_debut_year_count,total);renderDebuts(s.debut_trend||[],s.known_debut_year_count,total);
  document.querySelector('#overviewDirectoryCount').textContent=`${fmt(total)} รายการในระบบ`;
}
function renderPlatforms(rows,total){const root=document.querySelector('#platformChart');if(!rows.length){root.className='platform-bars empty-state';root.textContent='ยังไม่มีข้อมูล';return}root.className='platform-bars';const top=rows.slice(0,6);root.innerHTML=top.map(x=>{const p=pct(x.count,total);return `<div class="platform-row"><div class="platform-meta"><span class="platform-label"><i class="platform-dot"></i>${esc(platformName(x.platform))}</span><span class="platform-count">${fmt(x.count)}</span><span class="platform-pct">${p==null?'—':p+'%'}</span></div><div class="bar-track"><div class="bar-fill" style="width:${p==null?0:clamp(p,2,100)}%"></div></div></div>`}).join('')}
function lifecycleGroups(rows){const map=Object.fromEntries(rows.map(x=>[x.status,x.count||0]));return {active:map.active||0,other:(map.hiatus||0)+(map.inactive||0)+(map.unknown||0),graduated:map.graduated||0}}
function renderLifecycle(rows,total){const root=document.querySelector('#lifecycleChart');if(!rows.length){root.className='status-summary empty-state';root.textContent='ยังไม่มีข้อมูล';return}const g=lifecycleGroups(rows),den=Number.isFinite(total)&&total>0?total:g.active+g.other+g.graduated;const pa=pct(g.active,den)||0,po=pct(g.other,den)||0,pg=Math.max(0,100-pa-po);document.querySelector('#lifecycleTotal').textContent=`รวม ${fmt(den)}`;root.className='status-summary';root.innerHTML=`<div class="segmented-bar" aria-label="Active ${pa}% อื่น ๆ ${po}% Graduated ${pg}%"><span style="width:${pa}%"></span><i style="width:${po}%"></i><b style="width:${pg}%"></b></div><div class="status-tiles"><div class="status-tile"><header><span class="dot sky"></span>Active</header><strong style="color:var(--blue)">${fmt(g.active)}</strong><small>${pa}% • ตามทะเบียน</small></div><div class="status-tile"><header><span class="dot" style="background:var(--outline)"></span>อื่น ๆ / ไม่ทราบ</header><strong>${fmt(g.other)}</strong><small>${po}% • Hiatus / inactive / unknown</small></div><div class="status-tile"><header><span class="dot" style="background:var(--pink)"></span>Graduated</header><strong style="color:var(--pink)">${fmt(g.graduated)}</strong><small>${pg}% • ยุติกิจกรรม</small></div></div>`}
function renderClassification(total){const creators=state.creators;if(!creators.length||!Number.isFinite(total)){document.querySelector('#classificationText').textContent='—';return}const indie=creators.filter(c=>(c.agency||'Independent').toLowerCase()==='independent').length,agency=creators.length-indie,den=creators.length,ip=pct(indie,den)||0,ap=100-ip;document.querySelector('#classificationText').textContent=`Indie ${ip}% | Agency ${ap}%`;document.querySelector('#indieBar').style.width=ip+'%';document.querySelector('#agencyBar').style.width=ap+'%';document.querySelector('#indieCount').textContent=`อิสระ ${fmt(indie)} คน`;document.querySelector('#agencyCount').textContent=`สังกัด ${fmt(agency)} คน`}
function renderTrend(rows,known,total){const root=document.querySelector('#trendChart');const coverage=Number.isFinite(known)&&Number.isFinite(total)&&total?`${fmt(known)} / ${fmt(total)} รายการมีปีเดบิวต์`:'แสดงเฉพาะปีที่ทราบ';document.querySelector('#trendCoverage').textContent=coverage;if(rows.length<2){root.className='trend-wrap empty-state';root.textContent='ยังไม่มีข้อมูลเพียงพอ';return}root.className='trend-wrap';const W=720,H=230,pL=44,pR=22,pT=28,pB=34,vals=rows.map(x=>Number(x.cumulative_known_debuts)||0),max=Math.max(...vals,1),pts=rows.map((r,i)=>{const x=pL+i*(W-pL-pR)/Math.max(rows.length-1,1),y=H-pB-(Number(r.cumulative_known_debuts)||0)/max*(H-pT-pB);return{x,y,r}}),poly=pts.map(o=>`${o.x},${o.y}`).join(' '),area=`M ${pts[0].x} ${H-pB} L ${poly.replaceAll(',',' ')} L ${pts.at(-1).x} ${H-pB} Z`,grids=[0,.33,.66,1].map(k=>{const y=pT+k*(H-pT-pB);return `<line class="trend-grid" x1="${pL}" y1="${y}" x2="${W-pR}" y2="${y}"/>`}).join(''),dots=pts.map((o,i)=>`<circle class="trend-dot ${i===pts.length-1?'last':''}" cx="${o.x}" cy="${o.y}" r="4.5"><title>${o.r.year}: ${fmt(o.r.cumulative_known_debuts)}</title></circle><text class="trend-value" x="${o.x}" y="${o.y-11}" text-anchor="middle">${fmt(o.r.cumulative_known_debuts)}</text><text class="trend-label" x="${o.x}" y="${H-8}" text-anchor="middle">${o.r.year}</text>`).join('');root.innerHTML=`<svg class="trend-svg" viewBox="0 0 ${W} ${H}" role="img" aria-label="กราฟรายการสะสมที่มีข้อมูลปีเดบิวต์"><defs><linearGradient id="areaGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#5f3add" stop-opacity=".20"/><stop offset="1" stop-color="#5f3add" stop-opacity="0"/></linearGradient></defs>${grids}<path class="trend-area" d="${area}"/><polyline class="trend-line" points="${poly}"/>${dots}</svg>`}
function renderDebuts(rows,known,total){const root=document.querySelector('#debutList');const latest=[...rows].sort((a,b)=>b.year-a.year).slice(0,6);if(!latest.length){root.className='debut-list empty-state';root.textContent='ยังไม่มีข้อมูล';document.querySelector('#debutCoveragePct').textContent='—';return}root.className='debut-list';root.innerHTML=latest.map(r=>{const prev=rows.find(x=>x.year===r.year-1),y=Number(r.known_debuts)||0,py=prev?Number(prev.known_debuts)||0:null,delta=py>0?Math.round((y-py)/py*100):null;return `<div class="debut-row"><span>ปี ${r.year}</span><strong>${fmt(y)} คน</strong><span class="debut-yoy ${delta!=null&&delta<0?'negative':''}">${delta==null?'—':(delta>0?'+':'')+delta+'%'}</span></div>`}).join('');document.querySelector('#debutCoveragePct').textContent=Number.isFinite(known)&&Number.isFinite(total)&&total?`${Math.round(known/total*100)}%`:'—'}
function setupDirectory(){const platforms=[...new Set(state.creators.flatMap(c=>(c.platforms||[]).map(p=>p.name)))].sort();const pp=document.querySelector('#platformPills');pp.innerHTML=`<button class="filter-pill active" data-platform="">ทั้งหมด <b>${fmt(state.creators.length)}</b></button>`+platforms.map(p=>`<button class="filter-pill" data-platform="${esc(p)}"><span class="material-symbols-outlined">${platformIcons[p]||'link'}</span>${esc(platformName(p))}</button>`).join('');const statuses=['','active','hiatus','inactive','graduated','unknown'];document.querySelector('#statusPills').innerHTML=statuses.map((s,i)=>`<button class="filter-pill ${i===0?'active':''}" data-status="${s}">${s?esc(statusLabels[s]||s):'ทุกสถานะ'}</button>`).join('');pp.addEventListener('click',pillClick);document.querySelector('#statusPills').addEventListener('click',pillClick);document.querySelector('#searchInput').addEventListener('input',()=>{state.visible=12;filterDirectory()});document.querySelector('#sortSelect').addEventListener('change',e=>{state.sort=e.target.value;state.visible=12;filterDirectory()});document.querySelector('#loadMore').addEventListener('click',()=>{state.visible+=12;renderDirectory()});document.querySelector('#directoryTotal').textContent=fmt(state.creators.length);filterDirectory()}
function pillClick(e){const b=e.target.closest('.filter-pill');if(!b)return;const key=b.hasAttribute('data-platform')?'platform':'status',group=b.parentElement;group.querySelectorAll('.filter-pill').forEach(x=>x.classList.remove('active'));b.classList.add('active');state[key]=b.dataset[key]||'';state.visible=12;filterDirectory()}
function filterDirectory(){const q=document.querySelector('#searchInput').value.trim().toLocaleLowerCase('th');state.filtered=state.creators.filter(c=>(!q||`${c.name} ${c.agency||''}`.toLocaleLowerCase('th').includes(q))&&(!state.platform||(c.platforms||[]).some(p=>p.name===state.platform))&&(!state.status||c.status===state.status));state.filtered.sort((a,b)=>{if(state.sort==='debut-new')return (b.debut_year||0)-(a.debut_year||0)||a.name.localeCompare(b.name,'th');if(state.sort==='debut-old')return (a.debut_year||9999)-(b.debut_year||9999)||a.name.localeCompare(b.name,'th');return a.name.localeCompare(b.name,'th')});renderDirectory()}
function initial(name){return Array.from(String(name||'?').trim())[0]||'?'}function tone(name){let n=0;for(const ch of String(name))n=(n+ch.codePointAt(0))%4;return n?`tone-${n}`:''}
function creatorAction(c){const first=(c.platforms||[]).find(p=>p.url);return first?`<a class="creator-action" href="${esc(first.url)}" target="_blank" rel="noopener noreferrer">เปิดช่องทางสาธารณะ <span class="material-symbols-outlined" style="font-size:14px">arrow_forward</span></a>`:`<span class="creator-action" style="color:var(--muted)">ยังไม่มีลิงก์สาธารณะ</span>`}
function renderDirectory(){const rows=state.filtered.slice(0,state.visible);document.querySelector('#visibleCount').textContent=fmt(rows.length);document.querySelector('#resultCount').textContent=`แสดง ${fmt(rows.length)} จากทั้งหมด ${fmt(state.filtered.length)} รายการ`;const grid=document.querySelector('#creatorGrid');grid.innerHTML=rows.length?rows.map(c=>`<article class="card creator-card ${esc(c.status)}"><div><div class="creator-card-top"><div class="avatar ${tone(c.name)}">${esc(initial(c.name))}</div><span class="status-chip ${esc(c.status)}">${esc(statusLabels[c.status]||c.status)}</span></div><div class="creator-meta"><span class="agency-chip">${esc(c.agency||'Independent')}</span>${c.debut_year?`<span class="debut-year"><span class="material-symbols-outlined">calendar_today</span>${esc(c.debut_year)}</span>`:''}</div><h2>${esc(c.name)}</h2></div><div class="creator-card-bottom"><div class="platform-links">${(c.platforms||[]).map(p=>p.url?`<a class="platform-link" href="${esc(p.url)}" target="_blank" rel="noopener noreferrer" title="${esc(platformName(p.name))}"><span class="material-symbols-outlined">${platformIcons[p.name]||'link'}</span></a>`:`<span class="platform-link" title="${esc(platformName(p.name))}"><span class="material-symbols-outlined">${platformIcons[p.name]||'link'}</span></span>`).join('')}</div>${creatorAction(c)}</div></article>`).join(''):'<div class="card empty-state" style="grid-column:1/-1">ไม่พบรายการที่ตรงกับตัวกรอง</div>';document.querySelector('#loadMore').hidden=state.visible>=state.filtered.length}
function setupContribution(){document.querySelectorAll('.form-tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.form-tab').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.mode=b.dataset.mode;document.querySelector('#contributionMode').value=state.mode}));document.querySelector('#contributionForm').addEventListener('submit',submitContribution);document.querySelector('#downloadTemplate').addEventListener('click',downloadCsvTemplate)}
function submitContribution(e){e.preventDefault();const get=id=>document.querySelector(id).value.trim(),status=document.querySelector('input[name="formStatus"]:checked')?.value||'unknown',mode=get('#contributionMode'),name=get('#formName'),body=[`ประเภท: ${mode==='new'?'เพิ่ม VTuber ใหม่':'แจ้งแก้ไขข้อมูลเดิม'}`,`ชื่อ: ${name}`,`สังกัด/กลุ่ม: ${get('#formAffiliation')||'ไม่ระบุ'}`,`วัน/ปีเดบิวต์: ${get('#formDebut')||'ไม่ระบุ'}`,`สถานะ: ${statusLabels[status]||status}`,`YouTube: ${get('#formYoutube')||'ไม่ระบุ'}`,`X / Twitter: ${get('#formX')||'ไม่ระบุ'}`,`ช่องทางอื่น: ${get('#formOther')||'ไม่ระบุ'}`,'',`รายละเอียด/หลักฐาน: ${get('#formEvidence')||'ไม่ระบุ'}`,'','หมายเหตุ: กรุณาตรวจสอบว่าข้อมูลทั้งหมดเป็นข้อมูลสาธารณะก่อนส่ง'].join('\n');const title=`${mode==='new'?'[Add]':'[Update]'} ${name}`;window.open(`https://github.com/Icezaza2543/ThaiVtuberPublic/issues/new?title=${encodeURIComponent(title)}&body=${encodeURIComponent(body)}`,'_blank','noopener,noreferrer')}
function downloadCsvTemplate(){const csv='name,affiliation,debut_date_or_year,status,youtube_url,x_url,other_urls,evidence_url_or_note\n';const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='thaivtuberpublic-contribution-template.csv';document.body.appendChild(a);a.click();URL.revokeObjectURL(a.href);a.remove()}
function route(){const id=(location.hash||'#overview').slice(1),target=['overview','directory','about','contribute'].includes(id)?id:'overview';document.querySelectorAll('.page').forEach(x=>x.classList.toggle('page-active',x.id===target));document.querySelectorAll('[data-route]').forEach(x=>x.classList.toggle('active',x.dataset.route===target));document.querySelector('#navLinks').classList.remove('open');document.querySelector('#menuButton').setAttribute('aria-expanded','false');window.scrollTo({top:0,behavior:'instant'})}
window.addEventListener('hashchange',route);document.querySelector('#menuButton').addEventListener('click',e=>{const nav=document.querySelector('#navLinks'),open=nav.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(open))});load();
